### PR TITLE
Update PingCommand.java

### PR DESCRIPTION
**Pull request by kamcio96**
New line issue
http://scr.hu/1s1h/k1kh8

Btw, how configure gui and net on vmware/virtualbox?

### CODE REVIEW

**Comment by LSantha** [comment]
@kamcio96, thanks for the patch! It's merged.
On VirtualBox 5.0.14 under Ubuntu I use "Bridged Adapter" on the main NIC of the machine. For advanced settings, adapter type should be "PCNet-FAST III (Am79C973), also promiscuous mode "Allow All" and "Cable Connected" is selected. With this JNode will be in the same network domain as the NIC.

**Comment by kamcio96** [comment]
Last activity on forum was 2 years ago. Nobody on irc. Any other way to talk? Maybe gitter?

Is gui avalible with virtualbox?

**Comment by LSantha** [comment]
Select the VESA mode in the boot menu to see the GUI.

**Comment by LSantha** [comment]
@kamcio96, we mostly communicate via e-mail and the github facilities these days. You can create issues also if you have questions or want to discuss about a topic.

**Pull request merged**
