### PR TITLE
Further filesystem and partition table fixes

### PR DESCRIPTION
**Pull request by tmyroadctfig**
* Further fixes from my audit of HFS+ and ext2/3/4.
* Add support for some further ext4 features.
* Added more checks to IBM MBR detection.
* Add in test cases for some of the above changes.

### CODE REVIEW

**Comment by flesire** [comment]
Can someone could merge this pull request that include a lot of improvements for filesystem so we can continue to work on other improvements.

**Comment by ewoutp** [comment]
@flesire I would be happy to do so as soon as:

1 - The merge conflicts have been solved 
2 - I get a looks good to me from ypu after testing the updated branch

**Comment by manuelex20** [comment]
Hello! I saw this project interesting and I wanna contribute with it. I know a little of Java, too! I don't know what I should do. Please, if someone can help me to virtualize it in VMware to try JNode, i'll be thankful! My email's manuelex20@gmail.com

**Comment by tmyroadctfig** [comment]
I think I've fixed the merge conflicts. Can someone please review this again, and possibly merge the changes?

Thanks, Luke

**Comment by LSantha** [comment]
Hi @tmyroadctfig, 

I had a look at this PR and by running ./build.sh tests I get errors and failed tests for various FS tests. JNode master doesn't have this issue. Could you look into it please?
I'm glad to see your work and I'm happy to merge it as soon as we sort out related issues.

Thank you, Levente

**Comment by tmyroadctfig** [comment]
Hi @LSantha 

I've put in some further changes, and those tests appear to be passing for me now. If you get a chance to review this again it would be appreciated.

Thanks,

Luke

**Comment by LSantha** [comment]
Hi @tmyroadctfig 
The PR looks good for a merge so I've merged it.
Thanks a lot, Levente

**Comment by tmyroadctfig** [comment]
Thank you. Greatly appreciated!

Cheers, Luke

**Pull request merged**
